<a href='https://www.hexnbit.com/'> <img src='https://www.hexnbit.com/wp-content/uploads/2019/09/hexnbit_final_66px.png'/> </a>

# A3_Assignment

Mentioned below are the tasks, the solution for each tasks has to be appended by inserting a new cell below the task,
along with the following description:-
1. Why the method was used (if applicable)
2. Explanation of logic

### Task 1

Generate all integers between (100 and 200) both inclusive, using NumPy

In [13]:
import numpy as np
x = np.random.randint(low=100, high=201, size=100)
print(x)

[119 135 179 198 102 167 176 142 198 164 130 102 129 109 114 120 106 101
 130 162 111 183 177 187 177 154 108 154 188 161 118 158 102 160 196 105
 159 163 101 101 145 107 105 102 170 161 177 153 126 200 114 144 136 110
 110 141 139 157 135 168 160 150 186 165 109 189 196 141 151 187 196 116
 151 106 149 120 151 149 134 183 131 194 159 189 183 107 131 167 168 113
 144 111 167 109 147 150 135 127 182 136]


### Task2

Print all even integers from the array created in Task1

In [3]:
for i in x:
    if i%2==0:
        print(i)

120
100
184
184
138
124
184
178
168
154
176
170
188
152
170
164
122
174
172
112
168
188
138
156
160
162
138
174
194
164
190
160
106
172
194
110
126
138
148
138
168
166
188
126


### Task3
Create NumPy arrays to obtain given samples:-<br>
**Original array_Sample 1:**<br>
[1 0 0 0]<br>
**Original array_Sample 2:**<br>
[0 0 0 0]

In [11]:
y = np.random.randint(low=0, high=2, size=4)
print(y)
z=  np.random.randint(low=0, high=1, size=4)
print(z)

[1 0 0 0]
[0 0 0 0]


### Task4

Create a NumPy array of shape 5x5 and print the last 3 rows

In [23]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Task3
Write a programs to create following 3 arrays:- 


In [29]:
x=np.zeros(10)
y=np.ones(10)
print(x)
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [25]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Task4

Create an array of 25 random values
- Find the sum of all elements
- Print the element with maximum value and minimum value

In [31]:
x = np.random.randint(low=100, high=201, size=25)
print(x)
sum=0
for i in x:
    sum=sum+i
print(sum)

[104 150 140 146 151 151 110 181 122 136 180 153 113 170 101 126 152 163
 179 195 104 160 104 168 171]
3630


### Task5

Create an NumPy array of 100 values evenly spaced between 10 and 20

In [37]:
arr = np.arange(0, 100, 10)
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

### Task6
Write a NumPy program to create a 3x3x3 array with random values.


In [38]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.86651593 0.77725236 0.23426267]
  [0.21571919 0.98811159 0.45450746]
  [0.72901289 0.76567049 0.39183779]]

 [[0.90730478 0.93581478 0.53731149]
  [0.52835806 0.02080562 0.2635025 ]
  [0.76426941 0.10270685 0.87860126]]

 [[0.71737229 0.85622607 0.39934892]
  [0.65359543 0.53144775 0.66430731]
  [0.07448061 0.90464173 0.018484  ]]]


### Task7
Write a Python program to check that a string contains only a certain set of characters (in this case a-z, A-Z and 0-9).

**Hint:**<br>
Input: ABCDEFabcdef123450<br>
Output: True<br>


In [39]:
import re
def is_allowed_specific_char(string):
    charRe = re.compile(r'[^a-zA-Z0-9.]')
    string = charRe.search(string)
    return not bool(string)

inp=input()

print(is_allowed_specific_char(inp))

qw2
True


### Task8
Write a Python program to find sequences of lowercase letters joined with a underscore.

**Hint:**<br>
Input: aab_cbbbc<br>
Output: True


In [43]:
import re
def text_match(text):
        patterns = '_'
        if re.search(patterns,  text):
                return 'True'
        else:
                return 'False'

inp=input()

print(text_match(inp))


qp
False


### Task9
Write a Python program where a string will start with a specific number

**Hint:**<br>
Input: 5-2345861<br>
Output: True


In [45]:
import re
def match_num(string):
    text = re.compile(r"^5")
    if text.match(string):
        return True
    else:
        return False
    
inp=input()

print(match_num(inp))



5-ssgs
True


### Task10
- Input a string from user
- Write Python program to search if the entered string contains the keyword "HEX" in it.<br>
- The search must not be case sensitive.<br>
- The search must be able to look for multiple occurences of the keyword in the complete string.<br>
- For all occurences, print the keyword<bt>
- For all occurences, print the starting and ending position of the occurence in the entered string.<br>

**Hint:**<br>
    Check example output below for input string "Bitwise AND, BITWISE NOT, bitwise OR"

Enter your string: Bitwise AND, BITWISE NOT, bitwise OR

Found the keyword as:  Bit
Starting Position:  0
Ending Position:  3

Found the keyword as:  BIT
Starting Position:  13
Ending Position:  16

Found the keyword as:  bit
Starting Position:  26
Ending Position:  29

